mysite/food/urls.py
from . import views
from django.urls import path

app_name = "food"
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:item_id>/',views.detail,name='detail'),
    path('item/',views.item,name='item'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
]

mysite/food/models.py
from django.db import models


# Create your models here.
class Item(models.Model):
    
    def __str__(self):
        return self.item_name
    
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://cdn-icons-png.flaticon.com/512/1147/1147805.png")

mysite/food/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Item
from django.template import loader

# Create your views here.
def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list':item_list,
        
    }
    return render(request,'food/index.html',context)

def item(request):
    return HttpResponse('Enter the item')


# Geeting full detail view of the food
def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    
    context = {
        'item':item,
        
    }
    
    return render(request,'food/detail.html',context)

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Document</title>
        <link rel="stylesheet" href="{% static 'food/style.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </head>

	<body>
        <nav class='navbar navbar-dark bg-dark' href='#'>
            <a href="#" class="navbar-brand">FoodApp</a>

            <div class="navbar">
                <a class="nav-item nav-link" href="#">Add Item </a>
                <a class="nav-item nav-link" href="#">Delete Item </a>
                <a class="nav-item nav-link" href="#">View Item </a>
            </div>
        </nav>

    {% block body %}
    {% endblock %}
    
    </body>
</html>

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}


{% block body%}
<div class="container">

    <div class="row">

        <div class="col-md-6">
            <img height="300px" src="{{item.item_image}}" class= "card" />
        </div>

        <div class="col-md-6">
            <h1>{{item.item_name}}</h1>
            <h2>{{item.item_desc}}</h2>
            <h3>${{item.item_price}}</h3>   
        </div>

    </div>
</div>

{% endblock %}

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
    </head>
	<body>

        {% block body%}
        {%for item in item_list%}

        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" width="150px" src=" {{item.item_image}} "/>

            </div>

            <div class="col-md-4">
                <h3>{{item.item_name}}</h3>
                <h5>{{item.item_desc}}</h5>
                <h6>${{item.item_price}}</h6>
                
            </div>

            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success"">Details</a>
                
            </div>
        </div>

        {% endfor %}
        {% endblock %}

    </body>
</html>